name: build

on:
  workflow_call:
    outputs:
      image-ref:
        description: "Built image reference"
        value: ${{ jobs.build.outputs.image-ref }}

  push:
    branches: [ "master", "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    outputs:
      image-ref: ${{ steps.meta.outputs.image }}

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image name
        id: meta
        run: |
          IMAGE="${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "Building $IMAGE"

      - name: Build an image from Dockerfile
        run: docker build -t ${{ steps.meta.outputs.image }} .