name: build

on:
  workflow_call:
    outputs:
      image-ref:
        description: "Built image reference"
        value: ${{ jobs.build.outputs.image-ref }}

  push:
    branches: [ "master", "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    outputs:
      image-ref: ${{ steps.meta.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image name (lowercase)
        id: meta
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="${IMAGE_NAME}:${{ github.sha }}"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "Building $IMAGE"

      - name: Build an image from Dockerfile
        run: docker build -t ${{ steps.meta.outputs.image }} .

      # Save image so the Trivy job can load it
      - name: Save Docker image
        run: docker save ${{ steps.meta.outputs.image }} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          retention-days: 1